apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense-tracker
spec:
  template:
    spec:
      containers:
      - name: app
        image: ghcr.io/dakshayahuja/expense-frontend:2081a22d5f57
