apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dakshayahuja/k8s-gitops-delivery-pipeline.git
    targetRevision: HEAD
    path: manifests/core-infra
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
