apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expense-tracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dakshayahuja/k8s-gitops-delivery-pipeline.git
    targetRevision: HEAD
    path: manifests/expense-tracker
  destination:
    server: https://kubernetes.default.svc
    namespace: expense-tracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
