controller:
  replicas: 1
  metrics:
    enabled: true
  server:
    metrics:
      enabled: true
  repoServer:
    metrics:
      enabled: true

applicationSet:
  metrics:
    enabled: true

server:
  service:
    type: LoadBalancer
  ingress:
    enabled: false
  extraArgs:
  - --insecure
  - --rootpath=/argocd
  - --basehref=/argocd
  serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus

configs:
  params:
    server.insecure: true
    server.rootpath: /argocd
    server.basehref: /argocd
  secret: {}

dex:
  enabled: false

redis:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

repoServer:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
