controller:
  replicas: 1

server:
  service:
    type: LoadBalancer
  ingress:
    enabled: false
  extraArgs:
  - --insecure
  - --rootpath=/argocd

configs:
  params:
    server.insecure: true
    server.rootpath: /argocd
  secret: {}

dex:
  enabled: false

redis:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

repoServer:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
