controller:
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false

  ingressClass: nginx

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance

  publishService:
    enabled: true

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      namespaceSelector:
        any: true
      interval: 15s
      additionalLabels:
        release: kube-prometheus
