apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx
  namespace: expense-tracker
data:
  nginx.conf: |
    worker_processes auto;
    events { worker_connections 1024; }
    http {
      include       mime.types;
      default_type  application/octet-stream;
      sendfile on;

      upstream backend {
        server backend.expense-tracker.svc.cluster.local:8000;
      }

      server {
        listen 80;

        # Serve the SPA at /
        location / {
          root   /usr/share/nginx/html;
          try_files $uri $uri/ /index.html;
        }

        # Proxy API under /api
        location /api/ {
          proxy_pass         http://backend/;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Proto $scheme;
        }
      }
    }
