apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: expense-tracker

resources:
- namespace.yaml
- db-secret.yaml
- postgres.yaml
- backend.yaml
- frontend-configmap.yaml
- frontend.yaml
- ingress.yaml

patches:
- path: patches/patch-backend.yaml
  target:
    kind: Deployment
    name: backend
    namespace: expense-tracker
- path: patches/patch-frontend.yaml
  target:
    kind: Deployment
    name: frontend
    namespace: expense-tracker
