apiVersion: v1
kind: Secret
metadata:
  name: expense-db
  namespace: expense-tracker
type: Opaque
stringData:
  POSTGRES_DB: expenses
  POSTGRES_USER: expense
  POSTGRES_PASSWORD: expensetracker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: expense-tracker
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: expense-db
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: expense-tracker
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
