# manifests/expense-tracker/postgres-exporter-deploy.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pg-exporter-secret
  namespace: expense-tracker
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://expense:expensetracker@postgres:5432/expenses?sslmode=disable"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: expense-tracker
  labels: { app: postgres-exporter }
spec:
  replicas: 1
  selector: { matchLabels: { app: postgres-exporter } }
  template:
    metadata: { labels: { app: postgres-exporter } }
    spec:
      containers:
      - name: exporter
        image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: pg-exporter-secret
              key: DATA_SOURCE_NAME
        ports:
        - name: metrics
          containerPort: 9187
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: expense-tracker
  labels: { app: postgres-exporter }
spec:
  selector: { app: postgres-exporter }
  ports:
  - name: metrics
    port: 9187
    targetPort: 9187
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  namespaceSelector:
    matchNames: [ "expense-tracker" ]
  selector:
    matchLabels: { app: postgres-exporter }
  endpoints:
  - port: metrics
    interval: 15s
