name: build-all
on:
  push:
    branches: [main]
    paths:
      - "expense-tracker-app/**"
      - ".github/workflows/build-all.yaml"
      - "manifests/expense-tracker/**"

  workflow_dispatch:
    inputs:
      build_backend:
        type: boolean
        default: true
        description: Build & push backend image
      build_frontend:
        type: boolean
        default: true
        description: Build & push frontend image

permissions:
  contents: write
  packages: write
  id-token: write

concurrency:
  group: kustomize-image-bumps
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'expense-tracker-app/backend/**'
            frontend:
              - 'expense-tracker-app/frontend/**'

  build_backend:
    runs-on: ubuntu-latest
    needs: changes
    # run if files changed OR manual dispatch asked for backend
    if: needs.changes.outputs.backend == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_backend == 'true')
    outputs:
      tag: ${{ steps.meta.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute tag
        id: meta
        run: echo "TAG=${GITHUB_SHA::12}" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v6
        with:
          context: ./expense-tracker-app/backend
          push: true
          tags: |
            ghcr.io/dakshayahuja/expense-backend:${{ steps.meta.outputs.TAG }}
            ghcr.io/dakshayahuja/expense-backend:latest

  build_frontend:
    runs-on: ubuntu-latest
    needs: [changes, build_backend]
    # run if files changed OR manual dispatch asked for frontend
    if: needs.changes.outputs.frontend == 'true' || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_frontend == 'true')
    outputs:
      tag: ${{ steps.meta.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute tag
        id: meta
        run: echo "TAG=${GITHUB_SHA::12}" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v6
        with:
          context: ./expense-tracker-app/frontend
          push: true
          tags: |
            ghcr.io/dakshayahuja/expense-frontend:${{ steps.meta.outputs.TAG }}
            ghcr.io/dakshayahuja/expense-frontend:latest

  bump_manifests:
    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend]
    if: needs.build_backend.result == 'success' || needs.build_frontend.result == 'success'
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Rebase on latest main
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git pull --rebase origin ${{ github.ref_name }}
      - name: Update image tags that were built in this run
        shell: bash
        run: |
          BACKEND_PATCH=manifests/expense-tracker/patches/patch-backend.yaml
          FRONTEND_PATCH=manifests/expense-tracker/patches/patch-frontend.yaml

          # Update backend image tag in patch (if we built backend)
          if [ "${{ needs.build_backend.result }}" = "success" ]; then
            B_TAG='${{ needs.build_backend.outputs.tag }}'
            sed -i -E "s|(image:\s*ghcr\.io/dakshayahuja/expense-backend:).*|\1${B_TAG}|" "$BACKEND_PATCH"
          fi

          # Update frontend image tag in patch (if we built frontend)
          if [ "${{ needs.build_frontend.result }}" = "success" ]; then
            F_TAG='${{ needs.build_frontend.outputs.tag }}'
            sed -i -E "s|(image:\s*ghcr\.io/dakshayahuja/expense-frontend:).*|\1${F_TAG}|" "$FRONTEND_PATCH"
          fi

      - name: Compute commit message
        id: commit_msg
        run: |
          msg="ci: bump"
          if [ "${{ needs.build_backend.result }}" = "success" ]; then
            msg="$msg backend->${{ needs.build_backend.outputs.tag }}"
          fi
          if [ "${{ needs.build_frontend.result }}" = "success" ]; then
            msg="$msg frontend->${{ needs.build_frontend.outputs.tag }}"
          fi
          echo "message=$msg" >> "$GITHUB_OUTPUT"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.commit_msg.outputs.message }}
          branch: ${{ github.ref_name }}