name: build-frontend-manual
on:
  workflow_dispatch:
    inputs:
      bump_manifests:
        type: boolean
        default: true
        description: Update manifests with new frontend image

permissions:
  contents: write
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute tag
        id: meta
        run: echo "TAG=${GITHUB_SHA::12}" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v6
        with:
          context: ./expense-tracker-app/frontend
          push: true
          tags: |
            ghcr.io/dakshayahuja/expense-frontend:${{ steps.meta.outputs.TAG }}
            ghcr.io/dakshayahuja/expense-frontend:latest
          build-args: |
            VITE_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            VITE_API_URL=${{ secrets.VITE_API_URL }}

  bump-manifests:
    runs-on: ubuntu-latest
    needs: [build-frontend]
    if: github.event.inputs.bump_manifests == 'true'
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Rebase
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git pull --rebase origin ${{ github.ref_name }}
      - name: Update frontend image tag
        run: |
          sed -i -E "s|(image:\s*ghcr\\.io/dakshayahuja/expense-frontend:).*|\\1${{ needs.build-frontend.outputs.tag }}|" \
            manifests/expense-tracker/patches/patch-frontend.yaml
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(manual): bump frontend->${{ needs.build-frontend.outputs.tag }}"
          branch: ${{ github.ref_name }}