name: build-backend-manual
on:
  workflow_dispatch:
    inputs:
      bump_manifests:
        type: boolean
        default: true
        description: Update manifests with new backend image

permissions:
  contents: write
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io

jobs:
  build-backend:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute tag
        id: meta
        run: echo "TAG=${GITHUB_SHA::12}" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v6
        with:
          context: ./expense-tracker-app/backend
          push: true
          tags: |
            ghcr.io/dakshayahuja/expense-backend:${{ steps.meta.outputs.TAG }}
            ghcr.io/dakshayahuja/expense-backend:latest

  apply-backend-secret:
    name: Apply backend K8s Secret
    runs-on: ubuntu-latest
    needs: [build-backend]
    if: needs.build-backend.result == 'success'
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gha-k8s-secret

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name gitops-delivery-cluster --region us-east-1

      - name: Ensure namespace exists
        run: |
          kubectl get ns expense-tracker || kubectl create ns expense-tracker

      - name: Create/Update backend secret
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          kubectl -n expense-tracker create secret generic backend-secrets \
            --from-literal=GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID" \
            --from-literal=JWT_SECRET="$JWT_SECRET" \
            --dry-run=client -o yaml | kubectl apply -f -

  bump-manifests:
    runs-on: ubuntu-latest
    needs: [build-backend]
    if: github.event.inputs.bump_manifests == 'true'
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Rebase
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git pull --rebase origin ${{ github.ref_name }}
      - name: Update backend image tag
        run: |
          sed -i -E "s|(image:\s*ghcr\\.io/dakshayahuja/expense-backend:).*|\\1${{ needs.build-backend.outputs.tag }}|" \
            manifests/expense-tracker/patches/patch-backend.yaml
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(manual): bump backend->${{ needs.build-backend.outputs.tag }}"
          branch: ${{ github.ref_name }}